name: Node CI

on: [push]

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: ['12.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: First check
      run: |
        echo ${NPM_CONFIG_PREFIX}
        npm prefix -g
        node -pe process.env.npm_config_prefix
      shell: bash
      env:
        CI: true

    - name: tye unset npm_config_prefix
      run: |
        unset NPM_CONFIG_PREFIX
        echo ${NPM_CONFIG_PREFIX}
        npm prefix -g
        node -pe process.env.npm_config_prefix
      shell: bash
      env:
        CI: true
